// frontend/src/lib/components/file-browser/BreadcrumbNav.svelte
<script lang="ts">
  import type { FileItem } from '$lib/types';
  import { ChevronRight, Home } from '@lucide/svelte';

  type Props = {
    path: FileItem[];
    onNavigate: (item: FileItem) => void;
  };
  const { path, onNavigate }: Props = $props();

  // On mobile, collapse to first + last 2 with an ellipsis.
  const shouldCollapse = $derived(path.length > 3);
  const visiblePath = $derived(shouldCollapse ? [path[0], ...path.slice(-2)] : path);
</script>

<nav class="scrollbar-none flex items-center gap-0.5 overflow-x-auto text-sm sm:gap-1">
  {#each visiblePath as item, index (item.id)}
    {@const isFirst = index === 0}
    {@const isLast = index === visiblePath.length - 1}
    {@const showEllipsis = shouldCollapse && index === 1}
    <div class="flex shrink-0 items-center gap-0.5 sm:gap-1">
      {#if index > 0}
        {#if showEllipsis}
          <ChevronRight class="text-muted-foreground size-3.5 sm:size-4" />
          <span class="text-muted-foreground px-1">...</span>
        {/if}
        <ChevronRight class="text-muted-foreground size-3.5 sm:size-4" />
      {/if}
      <button
        onclick={() => onNavigate(item)}
        class="hover:bg-secondary flex items-center gap-1 rounded px-1.5 py-1 transition-colors sm:gap-1.5 sm:px-2"
      >
        {#if isFirst}<Home class="size-3.5" />{/if}
        <span
          class="max-w-[80px] truncate sm:max-w-[150px] {isLast
            ? 'font-medium'
            : 'text-muted-foreground'}"
        >
          {item.name}
        </span>
      </button>
    </div>
  {/each}
</nav>

// frontend/components/file-browser/breadcrumb-nav.tsx
"use client"

import { ChevronRight, Home } from "lucide-react"
import type { FileItem } from "@/lib/types"

interface BreadcrumbNavProps {
  path: FileItem[]
  onNavigate: (item: FileItem) => void
}

export function BreadcrumbNav({ path, onNavigate }: BreadcrumbNavProps) {
  // On mobile, show only first and last 2 items with ellipsis
  const shouldCollapse = path.length > 3
  const visiblePath = shouldCollapse
    ? [path[0], ...path.slice(-2)]
    : path

  return (
    <nav className="flex items-center gap-0.5 text-sm overflow-x-auto scrollbar-none sm:gap-1">
      {visiblePath.map((item, index) => {
        const isFirst = index === 0
        const isLast = index === visiblePath.length - 1
        const showEllipsis = shouldCollapse && index === 1

        return (
          <div key={item.id} className="flex shrink-0 items-center gap-0.5 sm:gap-1">
            {index > 0 && (
              <>
                {showEllipsis && (
                  <>
                    <ChevronRight className="size-3.5 text-muted-foreground sm:size-4" />
                    <span className="px-1 text-muted-foreground">...</span>
                  </>
                )}
                <ChevronRight className="size-3.5 text-muted-foreground sm:size-4" />
              </>
            )}
            <button
              onClick={() => onNavigate(item)}
              className="flex items-center gap-1 rounded px-1.5 py-1 transition-colors hover:bg-secondary sm:gap-1.5 sm:px-2"
            >
              {isFirst && <Home className="size-3.5" />}
              <span className={`truncate max-w-[80px] sm:max-w-[150px] ${isLast ? "font-medium" : "text-muted-foreground"}`}>
                {item.name}
              </span>
            </button>
          </div>
        )
      })}
    </nav>
  )
}
