// frontend/components/file-browser/track-details.tsx
"use client"

import { useState, useCallback, useMemo, useEffect, useRef } from "react"
import {
  X,
  Music,
  Disc3,
  User,
  Calendar,
  Clock,
  HardDrive,
  Waves,
  FileAudio,
  CheckCircle2,
  AlertCircle,
  Loader2,
  FileText,
  Fingerprint,
  ExternalLink,
  RotateCcw,
  Eye,
  Pause,
  Play,
  Timer,
  AlignLeft,
} from "lucide-react"
import { Button } from "@/components/ui/button"
import { Separator } from "@/components/ui/separator"
import { ScrollArea } from "@/components/ui/scroll-area"
import { Badge } from "@/components/ui/badge"
import { Tabs, TabsContent, TabsList, TabsTrigger } from "@/components/ui/tabs"
import { Slider } from "@/components/ui/slider"
import type { FileItem, LyricsStatus } from "@/lib/types"
import { cn } from "@/lib/utils"
import { resetSongEnrichment, getSongStreamUrl, parseSongId, fetchTrackLyrics } from "@/lib/api-client"
import { usePlayer } from "@/lib/player-context"

interface TrackDetailsProps {
  file: FileItem | null
  onClose: () => void
  onResetEnrichment?: () => void
}

function formatTime(seconds: number): string {
  if (!Number.isFinite(seconds) || Number.isNaN(seconds) || seconds < 0) return "0:00"
  const m = Math.floor(seconds / 60)
  const s = Math.floor(seconds % 60)
  return `${m}:${s.toString().padStart(2, "0")}`
}

export function TrackDetails({ file, onClose, onResetEnrichment }: TrackDetailsProps) {
  const [resetState, setResetState] = useState<"idle" | "loading" | "success" | "error">("idle")
  const [resetError, setResetError] = useState<string | null>(null)
  const { currentSong, isPlaying, currentTime, duration, playSong, togglePlay, seek } = usePlayer()

  const songId = file ? parseSongId(file.id) : null
  const isThisSong = currentSong?.id === songId && songId !== null

  const handlePlay = useCallback(() => {
    if (songId === null || !file?.metadata) return
    playSong({
      id: songId,
      title: file.metadata.title,
      artist: file.metadata.artist,
      streamUrl: getSongStreamUrl(songId),
    })
  }, [songId, file, playSong])

  const handleResetEnrichment = useCallback(async () => {
    if (songId === null) return
    setResetState("loading")
    setResetError(null)
    try {
      await resetSongEnrichment(songId)
      setResetState("success")
      onResetEnrichment?.()
      setTimeout(() => setResetState("idle"), 3000)
    } catch (err) {
      setResetState("error")
      setResetError(err instanceof Error ? err.message : "Failed to reset enrichment")
      setTimeout(() => { setResetState("idle"); setResetError(null) }, 5000)
    }
  }, [songId, onResetEnrichment])

  if (!file || file.type !== "audio" || !file.metadata) {
    return null
  }

  const { metadata } = file
  const playerCurrentTime = isThisSong ? currentTime : 0
  const playerDuration = isThisSong ? duration : 0
  const playerIsPlaying = isThisSong && isPlaying

  return (
    <div className="flex h-full max-h-full flex-col overflow-hidden border-l border-border bg-card">
      <div className="flex items-center justify-between border-b border-border px-4 py-3">
        <h2 className="font-semibold">Track Details</h2>
        <Button variant="ghost" size="icon" onClick={onClose} className="size-8">
          <X className="size-4" />
        </Button>
      </div>

      <ScrollArea className="flex-1 min-h-0">
        <div className="p-4">
          {/* Album Art and Title - Horizontal on mobile sheets */}
          <div className="flex gap-4 mb-4 sm:flex-col sm:gap-0">
            <div className="size-24 shrink-0 overflow-hidden rounded-lg bg-secondary sm:aspect-square sm:size-auto sm:mb-4">
              {metadata.albumArt ? (
                <img
                  src={metadata.albumArt}
                  alt={metadata.album}
                  className="size-full object-cover"
                  crossOrigin="anonymous"
                />
              ) : (
                <div className="flex size-full items-center justify-center">
                  <Music className="size-10 text-muted-foreground sm:size-16" />
                </div>
              )}
            </div>

            {/* Title and Artist */}
            <div className="min-w-0 flex-1 sm:text-center sm:mb-4">
              <h3 className="text-base font-semibold text-balance sm:text-lg">{metadata.title}</h3>
              <p className="text-sm text-muted-foreground sm:text-base">{metadata.artist}</p>
              {/* Status Badge - inline on mobile */}
              <div className="mt-2 sm:hidden">
                <StatusBadge status={metadata.enrichmentStatus} />
              </div>
            </div>
          </div>

          {/* Status Badge - Hidden on mobile (shown inline above) */}
          <div className="mb-4 hidden justify-center sm:flex">
            <StatusBadge status={metadata.enrichmentStatus} />
          </div>

          {/* Inline Player */}
          {songId !== null && (
            <div className="mb-4 rounded-lg border border-border bg-secondary/30 p-3">
              <div className="flex items-center justify-center">
                <Button
                  variant="ghost"
                  size="icon"
                  className={cn(
                    "size-10 rounded-full transition-all",
                    playerIsPlaying
                      ? "bg-primary text-primary-foreground hover:bg-primary/90"
                      : "hover:bg-primary/10 hover:text-primary"
                  )}
                  onClick={isThisSong ? togglePlay : handlePlay}
                  aria-label={playerIsPlaying ? "Pause" : "Play"}
                >
                  {playerIsPlaying ? (
                    <Pause className="size-4" />
                  ) : (
                    <Play className="size-4 translate-x-px" />
                  )}
                </Button>
              </div>
              <div className="mt-2 flex items-center gap-2">
                <span className="w-9 shrink-0 text-right text-xs tabular-nums text-muted-foreground">
                  {formatTime(playerCurrentTime)}
                </span>
                <Slider
                  value={[playerCurrentTime]}
                  max={playerDuration > 0 ? playerDuration : 1}
                  min={0}
                  step={0.01}
                  disabled={!isThisSong || playerDuration === 0}
                  className={cn("flex-1", !isThisSong && "opacity-40")}
                  onValueChange={([val]) => {
                    if (isThisSong && val !== undefined) seek(val)
                  }}
                  aria-label="Seek"
                />
                <span className="w-9 shrink-0 text-xs tabular-nums text-muted-foreground">
                  {formatTime(playerDuration)}
                </span>
              </div>
            </div>
          )}

          <Separator className="my-4" />

          {/* Tabs for different info */}
          <Tabs defaultValue="info" className="w-full">
            <TabsList className="grid w-full grid-cols-3">
              <TabsTrigger value="info">Info</TabsTrigger>
              <TabsTrigger value="lyrics">Lyrics</TabsTrigger>
              <TabsTrigger value="sources">Sources</TabsTrigger>
            </TabsList>

            <TabsContent value="info" className="mt-4 space-y-3">
              <InfoRow icon={Disc3} label="Album" value={metadata.album} />
              <InfoRow icon={User} label="Artist" value={metadata.artist} />
              <InfoRow icon={Calendar} label="Year" value={metadata.year > 0 ? metadata.year.toString() : "Unknown"} />
              <InfoRow icon={Music} label="Genre" value={metadata.genre} />
              <Separator className="my-3" />
              <InfoRow icon={Clock} label="Duration" value={formatDuration(metadata.duration)} />
              <InfoRow icon={FileAudio} label="Format" value={metadata.format} />
              {metadata.bitrate > 0 && (
                <InfoRow icon={Waves} label="Bitrate" value={`${metadata.bitrate} kbps`} />
              )}
              {metadata.sampleRate > 0 && (
                <InfoRow icon={Waves} label="Sample Rate" value={`${(metadata.sampleRate / 1000).toFixed(1)} kHz`} />
              )}
              <InfoRow icon={HardDrive} label="File Size" value={formatFileSize(metadata.fileSize)} />
              {metadata.fingerprint && (
                <>
                  <Separator className="my-3" />
                  <div className="space-y-1.5">
                    <div className="flex items-center gap-2 text-sm text-muted-foreground">
                      <Fingerprint className="size-4" />
                      <span>Audio Fingerprint</span>
                    </div>
                    <code className="block rounded bg-secondary px-2 py-1.5 font-mono text-xs break-all">
                      {metadata.fingerprint}
                    </code>
                  </div>
                </>
              )}
            </TabsContent>

            <TabsContent value="lyrics" className="mt-4">
              <LyricsPanel
                songId={songId}
                syncedLyrics={metadata.syncedLyrics}
                plainLyrics={metadata.plainLyrics}
                lyricsStatus={metadata.lyricsStatus}
                hasSyncedLyrics={metadata.hasSyncedLyrics}
                hasPlainLyrics={metadata.hasPlainLyrics}
                isInstrumental={metadata.isInstrumental}
                currentTimeMs={isThisSong ? currentTime * 1000 : null}
                onSeek={isThisSong ? (timeMs: number) => seek(timeMs / 1000) : undefined}
                lrclibUrl={metadata.sourceIds.lrclibId
                  ? `https://lrclib.net/api/get/${metadata.sourceIds.lrclibId}`
                  : (metadata.artist && metadata.title
                    ? `https://lrclib.net/search?q=${encodeURIComponent(`${metadata.artist} ${metadata.title}`)}`
                    : undefined)}
              />
            </TabsContent>

            <TabsContent value="sources" className="mt-4 space-y-3">
              <p className="text-sm text-muted-foreground">
                Metadata enrichment sources
              </p>
              {metadata.matchedBy && (
                <div className="rounded-lg bg-secondary/50 px-3 py-2">
                  <p className="text-xs text-muted-foreground mb-1">Matched via</p>
                  <p className="text-sm font-medium">{metadata.matchedBy}</p>
                </div>
              )}
              <div className="space-y-2">
                <SourceRow
                  name="AcoustID"
                  connected={Boolean(metadata.sourceIds.acoustIdTrackId)}
                  url={metadata.sourceIds.acoustIdTrackId
                    ? `https://acoustid.org/track/${metadata.sourceIds.acoustIdTrackId}`
                    : "https://acoustid.org"}
                  label={metadata.sourceIds.acoustIdTrackId
                    ? `acoustid.org/track/${metadata.sourceIds.acoustIdTrackId.slice(0, 8)}…`
                    : undefined}
                />
                <SourceRow
                  name="MusicBrainz Recording"
                  connected={Boolean(metadata.sourceIds.musicBrainzId)}
                  url={metadata.sourceIds.musicBrainzId
                    ? `https://musicbrainz.org/recording/${metadata.sourceIds.musicBrainzId}`
                    : "https://musicbrainz.org"}
                  label={metadata.sourceIds.musicBrainzId
                    ? `musicbrainz.org/recording/${metadata.sourceIds.musicBrainzId.slice(0, 8)}…`
                    : undefined}
                />
                {metadata.sourceIds.musicBrainzReleaseId && (
                  <SourceRow
                    name="MusicBrainz Release"
                    connected={true}
                    url={`https://musicbrainz.org/release/${metadata.sourceIds.musicBrainzReleaseId}`}
                    label={`musicbrainz.org/release/${metadata.sourceIds.musicBrainzReleaseId.slice(0, 8)}…`}
                  />
                )}
                <SourceRow
                  name="Spotify"
                  connected={Boolean(metadata.sourceIds.spotifyId)}
                  url={metadata.sourceIds.spotifyId
                    ? `https://open.spotify.com/track/${metadata.sourceIds.spotifyId}`
                    : "https://spotify.com"}
                  label={metadata.sourceIds.spotifyId
                    ? `open.spotify.com/track/${metadata.sourceIds.spotifyId.slice(0, 8)}…`
                    : undefined}
                />
                <SourceRow
                  name="LRCLIB (Lyrics)"
                  connected={Boolean(metadata.sourceIds.lrclibId)}
                  url={metadata.sourceIds.lrclibId
                    ? `https://lrclib.net/api/get/${metadata.sourceIds.lrclibId}`
                    : (metadata.artist && metadata.title
                      ? `https://lrclib.net/search?q=${encodeURIComponent(`${metadata.artist} ${metadata.title}`)}`
                      : "https://lrclib.net")}
                  label={metadata.sourceIds.lrclibId
                    ? `lrclib.net/api/get/${metadata.sourceIds.lrclibId}`
                    : (metadata.artist && metadata.title
                      ? `lrclib.net/search?q=${metadata.artist}+${metadata.title}`
                      : undefined)}
                />
              </div>
              <Separator className="my-3" />
              <Button
                variant="outline"
                className={cn(
                  "w-full",
                  resetState === "success" && "border-primary/50 text-primary",
                  resetState === "error" && "border-destructive/50 text-destructive"
                )}
                size="sm"
                disabled={resetState === "loading" || songId === null}
                onClick={handleResetEnrichment}
              >
                {resetState === "loading" ? (
                  <>
                    <Loader2 className="mr-1.5 size-3.5 animate-spin" />
                    Resetting…
                  </>
                ) : resetState === "success" ? (
                  <>
                    <CheckCircle2 className="mr-1.5 size-3.5" />
                    Queued for Re-enrichment
                  </>
                ) : resetState === "error" ? (
                  <>
                    <AlertCircle className="mr-1.5 size-3.5" />
                    Reset Failed
                  </>
                ) : (
                  <>
                    <RotateCcw className="mr-1.5 size-3.5" />
                    Re-enrich Metadata
                  </>
                )}
              </Button>
              {resetError && (
                <p className="text-xs text-destructive mt-1.5">{resetError}</p>
              )}
            </TabsContent>
          </Tabs>
        </div>
      </ScrollArea>

      {/* File Path */}
      <div className="border-t border-border p-3">
        <p className="text-xs text-muted-foreground truncate">
          <span className="font-medium">Path:</span> {file.path}
        </p>
      </div>
    </div>
  )
}

function InfoRow({
  icon: Icon,
  label,
  value,
}: {
  icon: React.ComponentType<{ className?: string }>
  label: string
  value: string
}) {
  return (
    <div className="flex items-center justify-between">
      <div className="flex items-center gap-2 text-sm text-muted-foreground">
        <Icon className="size-4" />
        <span>{label}</span>
      </div>
      <span className="text-sm font-medium">{value}</span>
    </div>
  )
}

function SourceRow({
  name,
  connected,
  url,
  label,
}: {
  name: string
  connected?: boolean
  url: string
  label?: string
}) {
  return (
    <div className="flex items-center justify-between gap-2 rounded-lg bg-secondary/50 px-3 py-2">
      <div className="flex items-center gap-2 min-w-0">
        {connected ? (
          <CheckCircle2 className="size-4 shrink-0 text-primary" />
        ) : (
          <div className="size-4 shrink-0 rounded-full border-2 border-muted-foreground/30" />
        )}
        <span className="text-sm shrink-0">{name}</span>
      </div>
      <a
        href={url}
        target="_blank"
        rel="noopener noreferrer"
        className={cn(
          "flex items-center gap-1.5 text-xs transition-colors min-w-0",
          connected
            ? "text-primary hover:text-primary/80"
            : "text-muted-foreground hover:text-foreground"
        )}
        title={url}
      >
        {label && <span className="truncate">{label}</span>}
        <ExternalLink className="size-3 shrink-0" />
      </a>
    </div>
  )
}

function StatusBadge({ status }: { status: string }) {
  switch (status) {
    case "complete":
      return (
        <Badge className="bg-primary/10 text-primary hover:bg-primary/20">
          <CheckCircle2 className="mr-1.5 size-3" />
          Enriched
        </Badge>
      )
    case "processing":
      return (
        <Badge className="bg-chart-2/10 text-chart-2 hover:bg-chart-2/20">
          <Loader2 className="mr-1.5 size-3 animate-spin" />
          Processing
        </Badge>
      )
    case "needsreview":
      return (
        <Badge className="bg-amber-500/10 text-amber-600 hover:bg-amber-500/20 dark:text-amber-500">
          <Eye className="mr-1.5 size-3" />
          Needs Review
        </Badge>
      )
    case "pending":
      return (
        <Badge variant="secondary">
          <Clock className="mr-1.5 size-3" />
          Pending
        </Badge>
      )
    case "failed":
      return (
        <Badge variant="destructive">
          <AlertCircle className="mr-1.5 size-3" />
          Failed
        </Badge>
      )
    default:
      return null
  }
}

function formatDuration(seconds: number): string {
  const mins = Math.floor(seconds / 60)
  const secs = seconds % 60
  return `${mins}:${secs.toString().padStart(2, "0")}`
}

function formatFileSize(bytes: number): string {
  const mb = bytes / (1024 * 1024)
  return `${mb.toFixed(1)} MB`
}

interface LrcLine {
  timeMs: number
  text: string
}

function parseLrc(lrc: string): LrcLine[] {
  const lines: LrcLine[] = []
  for (const raw of lrc.split("\n")) {
    const match = raw.match(/^\[(\d{2}):(\d{2})\.(\d{2,3})\]\s*(.*)$/)
    if (!match) continue
    const mins = parseInt(match[1], 10)
    const secs = parseInt(match[2], 10)
    const cs = parseInt(match[3].padEnd(3, "0"), 10)
    const timeMs = mins * 60000 + secs * 1000 + cs
    lines.push({ timeMs, text: match[4] ?? "" })
  }
  return lines
}

function LyricsStatusBadge({ status }: { status?: LyricsStatus }) {
  switch (status) {
    case "Fetched":
      return (
        <Badge className="bg-primary/10 text-primary hover:bg-primary/20 text-xs">
          <CheckCircle2 className="mr-1 size-3" />
          Lyrics Found
        </Badge>
      )
    case "Instrumental":
      return (
        <Badge className="bg-blue-500/10 text-blue-600 hover:bg-blue-500/20 dark:text-blue-400 text-xs">
          <Music className="mr-1 size-3" />
          Instrumental
        </Badge>
      )
    case "NotFound":
      return (
        <Badge variant="secondary" className="text-xs">
          <FileText className="mr-1 size-3" />
          No Lyrics Found
        </Badge>
      )
    case "Failed":
      return (
        <Badge variant="destructive" className="text-xs">
          <AlertCircle className="mr-1 size-3" />
          Fetch Failed
        </Badge>
      )
    case "NotFetched":
    default:
      return (
        <Badge variant="outline" className="text-xs text-muted-foreground">
          <Clock className="mr-1 size-3" />
          Not Fetched
        </Badge>
      )
  }
}

function LyricsPanel({
  songId,
  syncedLyrics: syncedLyricsFromProps,
  plainLyrics: plainLyricsFromProps,
  lyricsStatus,
  hasSyncedLyrics: hasSyncedFromProps,
  hasPlainLyrics: hasPlainFromProps,
  isInstrumental,
  currentTimeMs,
  onSeek,
  lrclibUrl,
}: {
  songId: number | null
  syncedLyrics?: string
  plainLyrics?: string
  lyricsStatus?: LyricsStatus
  hasSyncedLyrics?: boolean
  hasPlainLyrics?: boolean
  isInstrumental?: boolean
  currentTimeMs?: number | null
  onSeek?: (timeMs: number) => void
  lrclibUrl?: string
}) {
  const [showSynced, setShowSynced] = useState(true)
  const [loadedSynced, setLoadedSynced] = useState<string | null | undefined>(syncedLyricsFromProps)
  const [loadedPlain, setLoadedPlain] = useState<string | null | undefined>(plainLyricsFromProps)
  const [loadState, setLoadState] = useState<"idle" | "loading" | "error">("idle")

  const lineRefs = useRef<(HTMLDivElement | null)[]>([])
  const containerRef = useRef<HTMLDivElement>(null)
  const prevActiveRef = useRef(-1)

  // Flags: trust the API-provided booleans when content isn't preloaded in props
  const hasSynced = Boolean(loadedSynced) || Boolean(hasSyncedFromProps)
  const hasPlain = Boolean(loadedPlain) || Boolean(hasPlainFromProps)
  const hasAny = hasSynced || hasPlain

  // Content may not be preloaded (the /songs endpoint returns flags only, not full text).
  // Auto-fetch when we know lyrics exist but content isn't loaded yet.
  const needsLoad =
    hasAny &&
    !Boolean(loadedSynced) &&
    !Boolean(loadedPlain) &&
    loadState === "idle" &&
    songId !== null

  useEffect(() => {
    if (!needsLoad || songId === null) return
    setLoadState("loading")
    fetchTrackLyrics(songId)
      .then((data) => {
        setLoadedSynced(data.synced ?? undefined)
        setLoadedPlain(data.plain ?? undefined)
        setLoadState("idle")
      })
      .catch(() => {
        setLoadState("error")
      })
  }, [needsLoad, songId])

  const parsedLines = useMemo(
    () => (Boolean(loadedSynced) && showSynced ? parseLrc(loadedSynced!) : null),
    [loadedSynced, showSynced]
  )

  const activeLineIndex = useMemo(() => {
    if (!parsedLines || currentTimeMs == null || currentTimeMs < 0) return -1
    let active = -1
    for (let i = 0; i < parsedLines.length; i++) {
      if (parsedLines[i].timeMs <= currentTimeMs) active = i
      else break
    }
    return active
  }, [parsedLines, currentTimeMs])

  const isTracking = parsedLines != null && currentTimeMs != null && currentTimeMs >= 0

  useEffect(() => {
    prevActiveRef.current = -1
  }, [parsedLines])

  useEffect(() => {
    if (activeLineIndex < 0 || activeLineIndex === prevActiveRef.current) return
    prevActiveRef.current = activeLineIndex
    const el = lineRefs.current[activeLineIndex]
    const container = containerRef.current
    if (!el || !container) return

    const elRect = el.getBoundingClientRect()
    const containerRect = container.getBoundingClientRect()
    const offset = elRect.top - containerRect.top + container.scrollTop
    const targetScroll = offset - container.clientHeight / 2 + el.clientHeight / 2
    container.scrollTo({ top: Math.max(0, targetScroll), behavior: "smooth" })
  }, [activeLineIndex])

  if (isInstrumental) {
    return (
      <div className="flex flex-col items-center justify-center py-8 text-center gap-2">
        <Music className="size-10 text-muted-foreground opacity-40" />
        <p className="text-sm text-muted-foreground">This track is instrumental — no lyrics expected.</p>
        <LyricsStatusBadge status="Instrumental" />
      </div>
    )
  }

  if (loadState === "loading") {
    return (
      <div className="flex flex-col items-center justify-center py-8 text-center gap-2">
        <Loader2 className="size-8 text-muted-foreground animate-spin" />
        <p className="text-sm text-muted-foreground">Loading lyrics…</p>
      </div>
    )
  }

  if (loadState === "error") {
    return (
      <div className="flex flex-col items-center justify-center py-8 text-center gap-2">
        <AlertCircle className="size-8 text-destructive opacity-70" />
        <p className="text-sm text-muted-foreground">Failed to load lyrics.</p>
        <Button variant="outline" size="sm" onClick={() => setLoadState("idle")}>Retry</Button>
      </div>
    )
  }

  if (!hasAny) {
    return (
      <div className="flex flex-col items-center justify-center py-8 text-center gap-2">
        <FileText className="size-10 text-muted-foreground opacity-50" />
        <p className="text-sm text-muted-foreground">
          {lyricsStatus === "NotFound"
            ? "No lyrics found in LRCLIB for this track."
            : lyricsStatus === "Failed"
              ? "Lyrics fetch encountered an error."
              : "Lyrics have not been fetched yet — they are enriched automatically after a successful metadata match."}
        </p>
        <LyricsStatusBadge status={lyricsStatus} />
      </div>
    )
  }

  const contentSynced = loadedSynced
  const contentPlain = loadedPlain
  const showSyncedToggle = Boolean(contentSynced) && Boolean(contentPlain)

  return (
    <div className="space-y-3">
      <div className="flex items-center justify-between">
        <LyricsStatusBadge status={lyricsStatus} />
        {showSyncedToggle && (
          <div className="flex rounded-md border border-border overflow-hidden text-xs">
            <button
              className={cn(
                "px-2 py-1 flex items-center gap-1 transition-colors",
                showSynced
                  ? "bg-primary text-primary-foreground"
                  : "bg-transparent text-muted-foreground hover:text-foreground"
              )}
              onClick={() => setShowSynced(true)}
            >
              <Timer className="size-3" />
              Synced
            </button>
            <button
              className={cn(
                "px-2 py-1 flex items-center gap-1 transition-colors",
                !showSynced
                  ? "bg-primary text-primary-foreground"
                  : "bg-transparent text-muted-foreground hover:text-foreground"
              )}
              onClick={() => setShowSynced(false)}
            >
              <AlignLeft className="size-3" />
              Plain
            </button>
          </div>
        )}
        {contentSynced && !contentPlain && (
          <Badge variant="outline" className="text-xs text-muted-foreground gap-1">
            <Timer className="size-3" />
            Synced LRC
          </Badge>
        )}
        {!contentSynced && contentPlain && (
          <Badge variant="outline" className="text-xs text-muted-foreground gap-1">
            <AlignLeft className="size-3" />
            Plain text
          </Badge>
        )}
      </div>

      <div
        ref={containerRef}
        className="rounded-lg bg-secondary/50 p-4 max-h-72 overflow-y-auto scroll-smooth"
      >
        {parsedLines ? (
          <div className="font-sans text-sm leading-relaxed">
            {parsedLines.map((line, i) => {
              const isActive = isTracking && i === activeLineIndex
              const isPast = isTracking && activeLineIndex >= 0 && i < activeLineIndex
              const isFuture = isTracking && activeLineIndex >= 0 && i > activeLineIndex

              return (
                <div
                  key={i}
                  ref={(el) => { lineRefs.current[i] = el }}
                  className={cn(
                    "flex gap-2 rounded-sm px-1 -mx-1 py-0.5 transition-all duration-300",
                    isActive && "bg-primary/10 text-primary font-semibold",
                    isPast && "text-muted-foreground",
                    isFuture && "text-muted-foreground/50",
                    !isTracking && "text-foreground",
                    onSeek && "cursor-pointer hover:bg-primary/5",
                  )}
                  onClick={onSeek ? () => onSeek(line.timeMs) : undefined}
                >
                  <span className={cn(
                    "shrink-0 text-xs font-mono w-12 pt-0.5",
                    isActive ? "text-primary/70" : "text-muted-foreground/60"
                  )}>
                    {formatLrcTime(line.timeMs)}
                  </span>
                  <span className={cn("flex-1", !line.text && "opacity-0 select-none")}>
                    {line.text || "·"}
                  </span>
                </div>
              )
            })}
          </div>
        ) : (
          <pre className="whitespace-pre-wrap font-sans text-sm leading-relaxed">
            {showSynced ? contentSynced : contentPlain}
          </pre>
        )}
      </div>

      {lrclibUrl && (
        <div className="flex items-center gap-1.5 text-xs text-muted-foreground">
          <span>Source:</span>
          <a
            href={lrclibUrl}
            target="_blank"
            rel="noopener noreferrer"
            className="inline-flex items-center gap-1 text-primary hover:text-primary/80 transition-colors"
          >
            LRCLIB
            <ExternalLink className="size-3" />
          </a>
        </div>
      )}
    </div>
  )
}

function formatLrcTime(ms: number): string {
  const totalSecs = Math.floor(ms / 1000)
  const mins = Math.floor(totalSecs / 60)
  const secs = totalSecs % 60
  return `${mins}:${secs.toString().padStart(2, "0")}`
}

// frontend/src/lib/components/file-browser/TrackDetails.svelte
<script lang="ts">
  import type { FileItem } from '$lib/types';
  import { Button } from '$lib/components/ui/button';
  import { Separator } from '$lib/components/ui/separator';
  import { ScrollArea } from '$lib/components/ui/scroll-area';
  import * as Tabs from '$lib/components/ui/tabs';
  import { Slider } from '$lib/components/ui/slider';
  import {
    X,
    Music,
    Disc3,
    User,
    Calendar,
    Clock,
    HardDrive,
    Waves,
    FileAudio,
    CheckCircle2,
    AlertCircle,
    Loader2,
    Fingerprint,
    RotateCcw,
    Pause,
    Play
  } from '@lucide/svelte';
  import { cn } from '$lib/utils';
  import {
    resetSongEnrichment,
    getSongStreamUrl,
    parseSongId
  } from '$lib/api-client';
  import { lrclibWebSearchUrl, lrclibWebUrl } from '$lib/lrclib-url';
  import { acoustIdSourceConnected, lrclibSourceConnected } from '$lib/source-connection';
  import { playerStore } from '$lib/stores/player.svelte';
  import InfoRow from './InfoRow.svelte';
  import SourceRow from './SourceRow.svelte';
  import StatusBadge from './StatusBadge.svelte';
  import LyricsPanel from './LyricsPanel.svelte';

  type Props = {
    file: FileItem | null;
    onClose: () => void;
    onResetEnrichment?: () => void;
  };
  const { file, onClose, onResetEnrichment }: Props = $props();

  let resetState = $state<'idle' | 'loading' | 'success' | 'error'>('idle');
  let resetError = $state<string | null>(null);

  function formatTime(seconds: number): string {
    if (!Number.isFinite(seconds) || Number.isNaN(seconds) || seconds < 0) return '0:00';
    const m = Math.floor(seconds / 60);
    const s = Math.floor(seconds % 60);
    return `${m}:${s.toString().padStart(2, '0')}`;
  }

  function formatDuration(seconds: number): string {
    const mins = Math.floor(seconds / 60);
    const secs = seconds % 60;
    return `${mins}:${secs.toString().padStart(2, '0')}`;
  }

  function formatFileSize(bytes: number): string {
    const mb = bytes / (1024 * 1024);
    return `${mb.toFixed(1)} MB`;
  }

  const songId = $derived(file ? parseSongId(file.id) : null);
  const isThisSong = $derived(
    playerStore.currentSong?.id === songId && songId !== null
  );

  function handlePlay() {
    if (songId === null || !file?.metadata) return;
    void playerStore.playSong({
      id: songId,
      title: file.metadata.title,
      artist: file.metadata.artist,
      streamUrl: getSongStreamUrl(songId)
    });
  }

  async function handleResetEnrichment() {
    if (songId === null) return;
    resetState = 'loading';
    resetError = null;
    try {
      await resetSongEnrichment(songId);
      resetState = 'success';
      onResetEnrichment?.();
      setTimeout(() => (resetState = 'idle'), 3000);
    } catch (err) {
      resetState = 'error';
      resetError = err instanceof Error ? err.message : 'Failed to reset enrichment';
      setTimeout(() => {
        resetState = 'idle';
        resetError = null;
      }, 5000);
    }
  }

  const playerCurrentTime = $derived(isThisSong ? playerStore.currentTime : 0);
  const playerDuration = $derived(isThisSong ? playerStore.duration : 0);
  const playerIsPlaying = $derived(isThisSong && playerStore.isPlaying);
</script>

{#if file && file.type === 'audio' && file.metadata}
  {@const metadata = file.metadata}
  <div class="border-border bg-card flex h-full max-h-full flex-col overflow-hidden border-l">
    <div class="border-border flex items-center justify-between border-b px-4 py-3">
      <h2 class="font-semibold">Track Details</h2>
      <Button variant="ghost" size="icon" onclick={onClose} class="size-8">
        <X class="size-4" />
      </Button>
    </div>

    <ScrollArea class="min-h-0 flex-1">
      <div class="p-4">
        <div class="mb-4 flex gap-4 sm:mb-0 sm:flex-col sm:gap-0">
          <div
            class="bg-secondary size-24 shrink-0 overflow-hidden rounded-lg sm:mb-4 sm:aspect-square sm:size-auto"
          >
            {#if metadata.albumArt}
              <img
                src={metadata.albumArt}
                alt={metadata.album}
                class="size-full object-cover"
                crossorigin="anonymous"
              />
            {:else}
              <div class="flex size-full items-center justify-center">
                <Music class="text-muted-foreground size-10 sm:size-16" />
              </div>
            {/if}
          </div>

          <div class="min-w-0 flex-1 sm:mb-4 sm:text-center">
            <h3 class="text-base font-semibold text-balance sm:text-lg">{metadata.title}</h3>
            <p class="text-muted-foreground text-sm sm:text-base">{metadata.artist}</p>
            <div class="mt-2 sm:hidden">
              <StatusBadge status={metadata.enrichmentStatus} />
            </div>
          </div>
        </div>

        <div class="mb-4 hidden justify-center sm:flex">
          <StatusBadge status={metadata.enrichmentStatus} />
        </div>

        {#if songId !== null}
          <div class="border-border bg-secondary/30 mb-4 rounded-lg border p-3">
            <div class="flex items-center justify-center">
              <Button
                variant="ghost"
                size="icon"
                class={cn(
                  'size-10 rounded-full transition-all',
                  playerIsPlaying
                    ? 'bg-primary text-primary-foreground hover:bg-primary/90'
                    : 'hover:bg-primary/10 hover:text-primary'
                )}
                onclick={isThisSong ? () => playerStore.togglePlay() : handlePlay}
                aria-label={playerIsPlaying ? 'Pause' : 'Play'}
              >
                {#if playerIsPlaying}
                  <Pause class="size-4" />
                {:else}
                  <Play class="size-4 translate-x-px" />
                {/if}
              </Button>
            </div>
            <div class="mt-2 flex items-center gap-2">
              <span class="text-muted-foreground w-9 shrink-0 text-right text-xs tabular-nums">
                {formatTime(playerCurrentTime)}
              </span>
              <Slider
                type="single"
                value={playerCurrentTime}
                max={playerDuration > 0 ? playerDuration : 1}
                min={0}
                step={0.01}
                disabled={!isThisSong || playerDuration === 0}
                class={cn('flex-1', !isThisSong && 'opacity-40')}
                onValueChange={(val) => {
                  if (isThisSong && typeof val === 'number') playerStore.seek(val);
                }}
                aria-label="Seek"
              />
              <span class="text-muted-foreground w-9 shrink-0 text-xs tabular-nums">
                {formatTime(playerDuration)}
              </span>
            </div>
          </div>
        {/if}

        <Separator class="my-4" />

        <Tabs.Root value="info" class="w-full">
          <Tabs.List class="grid w-full grid-cols-3">
            <Tabs.Trigger value="info">Info</Tabs.Trigger>
            <Tabs.Trigger value="lyrics">Lyrics</Tabs.Trigger>
            <Tabs.Trigger value="sources">Sources</Tabs.Trigger>
          </Tabs.List>

          <Tabs.Content value="info" class="mt-4 space-y-3">
            <InfoRow icon={Disc3} label="Album" value={metadata.album} />
            <InfoRow icon={User} label="Artist" value={metadata.artist} />
            <InfoRow
              icon={Calendar}
              label="Year"
              value={metadata.year > 0 ? metadata.year.toString() : 'Unknown'}
            />
            <InfoRow icon={Music} label="Genre" value={metadata.genre} />
            <Separator class="my-3" />
            <InfoRow icon={Clock} label="Duration" value={formatDuration(metadata.duration)} />
            <InfoRow icon={FileAudio} label="Format" value={metadata.format} />
            {#if metadata.bitrate > 0}
              <InfoRow icon={Waves} label="Bitrate" value={`${metadata.bitrate} kbps`} />
            {/if}
            {#if metadata.sampleRate > 0}
              <InfoRow
                icon={Waves}
                label="Sample Rate"
                value={`${(metadata.sampleRate / 1000).toFixed(1)} kHz`}
              />
            {/if}
            <InfoRow icon={HardDrive} label="File Size" value={formatFileSize(metadata.fileSize)} />
            {#if metadata.fingerprint}
              <Separator class="my-3" />
              <div class="space-y-1.5">
                <div class="text-muted-foreground flex items-center gap-2 text-sm">
                  <Fingerprint class="size-4" />
                  <span>Audio Fingerprint</span>
                </div>
                <code class="bg-secondary block rounded px-2 py-1.5 font-mono text-xs break-all">
                  {metadata.fingerprint}
                </code>
              </div>
            {/if}
          </Tabs.Content>

          <Tabs.Content value="lyrics" class="mt-4">
            <LyricsPanel
              {songId}
              syncedLyrics={metadata.syncedLyrics}
              plainLyrics={metadata.plainLyrics}
              lyricsStatus={metadata.lyricsStatus}
              hasSyncedLyrics={metadata.hasSyncedLyrics}
              hasPlainLyrics={metadata.hasPlainLyrics}
              isInstrumental={metadata.isInstrumental}
              currentTimeMs={isThisSong ? playerStore.currentTime * 1000 : null}
              onSeek={isThisSong ? (timeMs: number) => playerStore.seek(timeMs / 1000) : undefined}
              lrclibUrl={lrclibWebUrl(metadata.artist, metadata.title)}
            />
          </Tabs.Content>

          <Tabs.Content value="sources" class="mt-4 space-y-3">
            <p class="text-muted-foreground text-sm">Metadata enrichment sources</p>
            {#if metadata.matchedBy}
              <div class="bg-secondary/50 rounded-lg px-3 py-2">
                <p class="text-muted-foreground mb-1 text-xs">Matched via</p>
                <p class="text-sm font-medium">{metadata.matchedBy}</p>
              </div>
            {/if}
            <div class="space-y-2">
              <SourceRow
                name="AcoustID"
                connected={acoustIdSourceConnected(
                  metadata.sourceIds?.acoustIdTrackId,
                  metadata.matchedBy
                )}
                url={metadata.sourceIds?.acoustIdTrackId
                  ? `https://acoustid.org/track/${metadata.sourceIds.acoustIdTrackId}`
                  : 'https://acoustid.org'}
                label={metadata.sourceIds?.acoustIdTrackId
                  ? `acoustid.org/track/${metadata.sourceIds.acoustIdTrackId.slice(0, 8)}…`
                  : undefined}
              />
              <SourceRow
                name="MusicBrainz Recording"
                connected={Boolean(metadata.sourceIds?.musicBrainzId)}
                url={metadata.sourceIds?.musicBrainzId
                  ? `https://musicbrainz.org/recording/${metadata.sourceIds.musicBrainzId}`
                  : 'https://musicbrainz.org'}
                label={metadata.sourceIds?.musicBrainzId
                  ? `musicbrainz.org/recording/${metadata.sourceIds.musicBrainzId.slice(0, 8)}…`
                  : undefined}
              />
              {#if metadata.sourceIds?.musicBrainzReleaseId}
                <SourceRow
                  name="MusicBrainz Release"
                  connected={true}
                  url={`https://musicbrainz.org/release/${metadata.sourceIds.musicBrainzReleaseId}`}
                  label={`musicbrainz.org/release/${metadata.sourceIds.musicBrainzReleaseId.slice(0, 8)}…`}
                />
              {/if}
              <SourceRow
                name="Spotify"
                connected={Boolean(metadata.sourceIds?.spotifyId)}
                url={metadata.sourceIds?.spotifyId
                  ? `https://open.spotify.com/track/${metadata.sourceIds.spotifyId}`
                  : 'https://spotify.com'}
                label={metadata.sourceIds?.spotifyId
                  ? `open.spotify.com/track/${metadata.sourceIds.spotifyId.slice(0, 8)}…`
                  : undefined}
              />
              <SourceRow
                name="LRCLIB (Lyrics)"
                connected={lrclibSourceConnected({
                  lrclibId: metadata.sourceIds?.lrclibId,
                  lyricsStatus: metadata.lyricsStatus,
                  artist: metadata.artist,
                  title: metadata.title,
                  enrichmentStatus: metadata.enrichmentStatus
                })}
                url={lrclibWebUrl(metadata.artist, metadata.title)}
                label={lrclibWebSearchUrl(metadata.artist, metadata.title)
                  ? 'lrclib.net/search/…'
                  : undefined}
              />
            </div>
            <Separator class="my-3" />
            <Button
              variant="outline"
              class={cn(
                'w-full',
                resetState === 'success' && 'border-primary/50 text-primary',
                resetState === 'error' && 'border-destructive/50 text-destructive'
              )}
              size="sm"
              disabled={resetState === 'loading' || songId === null}
              onclick={handleResetEnrichment}
            >
              {#if resetState === 'loading'}
                <Loader2 class="mr-1.5 size-3.5 animate-spin" />
                Resetting…
              {:else if resetState === 'success'}
                <CheckCircle2 class="mr-1.5 size-3.5" />
                Queued for Re-enrichment
              {:else if resetState === 'error'}
                <AlertCircle class="mr-1.5 size-3.5" />
                Reset Failed
              {:else}
                <RotateCcw class="mr-1.5 size-3.5" />
                Re-enrich Metadata
              {/if}
            </Button>
            {#if resetError}
              <p class="text-destructive mt-1.5 text-xs">{resetError}</p>
            {/if}
          </Tabs.Content>
        </Tabs.Root>
      </div>
    </ScrollArea>

    <div class="border-border border-t p-3">
      <p class="text-muted-foreground truncate text-xs">
        <span class="font-medium">Path:</span>
        {file.path}
      </p>
    </div>
  </div>
{/if}
