// frontend/components/landing/cta-section.tsx
import { Button } from "@/components/ui/button"
import { Star, Github } from "lucide-react"

export function CTASection() {
  return (
    <section className="py-24 px-6 border-t border-border">
      <div className="max-w-3xl mx-auto text-center">
        <h2 className="text-3xl md:text-4xl font-bold mb-4">
          Ready to organize your library?
        </h2>
        <p className="text-muted-foreground text-lg mb-8 max-w-xl mx-auto">
          Stop fighting with messy filenames. Let MusicHoarder do the heavy lifting.
        </p>
        
        <div className="flex flex-col sm:flex-row items-center justify-center gap-4">
          <Button size="lg" className="gap-2 px-8 h-12 text-base font-medium" asChild>
            <a href="https://github.com/Jeffreyyvdb/MusicHoarder" target="_blank" rel="noopener noreferrer">
              <Star className="w-5 h-5" />
              Star on GitHub
            </a>
          </Button>
          <Button size="lg" variant="outline" className="gap-2 px-8 h-12 text-base font-medium" asChild>
            <a href="https://github.com/Jeffreyyvdb/MusicHoarder" target="_blank" rel="noopener noreferrer">
              <Github className="w-5 h-5" />
              View Documentation
            </a>
          </Button>
        </div>
      </div>
    </section>
  )
}

// frontend/src/lib/components/landing/CTASection.svelte
<script lang="ts">
  import { Button } from '$lib/components/ui/button';
  import GithubIcon from '$lib/components/GithubIcon.svelte';
  import { Star } from '@lucide/svelte';
</script>

<section class="border-border border-t px-6 py-24">
  <div class="mx-auto max-w-3xl text-center">
    <h2 class="mb-4 text-3xl font-bold md:text-4xl">Ready to organize your library?</h2>
    <p class="text-muted-foreground mx-auto mb-8 max-w-xl text-lg">
      Stop fighting with messy filenames. Let MusicHoarder do the heavy lifting.
    </p>

    <div class="flex flex-col items-center justify-center gap-4 sm:flex-row">
      <Button
        size="lg"
        class="h-12 gap-2 px-8 text-base font-medium"
        href="https://github.com/Jeffreyyvdb/MusicHoarder"
        target="_blank"
        rel="noopener noreferrer"
      >
        <Star class="h-5 w-5" />
        Star on GitHub
      </Button>
      <Button
        size="lg"
        variant="outline"
        class="h-12 gap-2 px-8 text-base font-medium"
        href="https://github.com/Jeffreyyvdb/MusicHoarder"
        target="_blank"
        rel="noopener noreferrer"
      >
        <GithubIcon class="h-5 w-5" />
        View Documentation
      </Button>
    </div>
  </div>
</section>
